### ISSUE TITLE
Note whether guide has been tested on K2

### ISSUE THREAD

**Issue by logi** [JohnJ80/Karoo-App-Sideloading#1]
There is no such thing as sending messages on github, so please don't take it badly that I opened an issue.

**Comment by JohnJ80** [comment]
No worries. 

I haven’t tested it yet but the adb tools work just fine on K2 so it shouldn’t be an issue. 

There could be an issue with an apk not being supported on this version of Android (8.0 vs 6.0 on K1) but that means it just won’t run. Can’t see how that would hurt the K2. 

The Karoo software are just applications on Android. Nothing more.

**Comment by logi** [comment]
Yeah. I'll try it myself if they eventually get around to letting me complete the pre-order and even ship it and then either comment here or send you a pull request, depending.

**Comment by JohnJ80** [comment]
Yes. I'd try it myself but I'm in the the ATG in the middle of testing/debugging an issue and this would wreck that.

HH has long been open about wanting to have an app store and from reading the DCRainmaker review, they have an SDK out there for third party developers to write apps. Based on that, I can't see how this is going to be an issue.  It's Android 8.0 on the K2 and it's open because you can get to the developer options through the settings app the same way you can on the K1 through Android 6.0.  

So, I'll marked this closed with that comment.  Love to hear about your experiences after you get yours.
